sudo: required 

env:
  - NODE_ENV=development

services:
  - docker

before_install:
  - docker build -t salar118/mywish-api -f Dockerfile .

script:
  - docker run salar118/mywish-api npm test -- --coverage
